Application "com.arm.cmsis.pack.installer" could not be found in the …
ARM-software/cmsis-pack-eclipse pull request #109
Opened 2023-07-18 05:08 UTC by andrewmclachlanadi

Fix for Application "com.arm.cmsis.pack.installer" could not be found in the registry #108

CMSIS-Pack command line installer IApplication is not found in the registry.

-application com.arm.cmsis.pack.installer -help results in Application "com.arm.cmsis.pack.installer" could not be found in the registry.

The following is missing from the plugin.xml in com.arm.cmsis.pack.installer.

<extension
         id="com.arm.cmsis.pack.installer"
         name="CMSIS-Pack command line installer"
         point="org.eclipse.core.runtime.applications">
      <application
            cardinality="singleton-global"
            thread="main"
            visible="true">
         <run
               class="com.arm.cmsis.pack.installer.ClPackInstaller">
         </run>
      </application>
   </extension>

2023-07-18 07:18 UTC, edriouk requested changes

2023-07-18 07:18 UTC, edriouk commented on com.arm.cmsis.pack.installer/plugin.xml
> +               class="com.arm.cmsis.pack.installer.ClPackInstaller">
class com.arm.cmsis.pack.installer.ClPackInstaller is missing. It needs to be added to the repository.

2023-07-18 10:20 UTC, andrewmclachlanadi commented
All set. Added the necessary files and modifications for this wee enhancement. Thanks for your patience and review.

2023-07-18 10:41 UTC, edriouk approved these changes

2023-07-18 11:12 UTC, andrewmclachlanadi commented
Thanks for the review @edriouk ! Appreciated. Thanks in advance for the merge :)

2023-07-18 11:17 UTC, merged

2023-07-18 11:24 UTC, edriouk commented
Thank you for the contribution :)

2023-07-20 08:59 UTC, edriouk commented
Hi Andrew, 
I'd like to draw you attention to CMSIS-Toolbox (https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases).
That provides a set of command-line tools to work with software packs in Open-CMSIS-Pack format.
The tools include **cpackget** executable  that allows to download and install CMSIS-Packs.

2023-07-21 07:01 UTC, andrewmclachlanadi commented
Thanks @edriouk .  https://github.com/Open-CMSIS-Pack/cmsis-toolbox looks very useful!

I assume that there are efforts here are because of easier integration with other IDEs like VS Code? Tag @JonatanAntoni